# Generated by Django 4.2.4 on 2023-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woo', '0005_wooalgoorder_woo_algo_order_type_is_sell_or_buy_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wooalgoorder',
            name='algo_type',
            field=models.CharField(choices=[('STOP', 'Stop'), ('OCO', 'Oco'), ('TRAILING_STOP', 'Trailing Stop'), ('BRACKET', 'Bracket')], default='STOP', max_length=20),
        ),
        migrations.AlterField(
            model_name='wooalgoorder',
            name='side',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4),
        ),
        migrations.AlterField(
            model_name='wooalgoorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PARTIAL_FILLED', 'Partial Filled'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='wooalgoorder',
            name='type',
            field=models.CharField(choices=[('LIMIT', 'Limit'), ('MARKET', 'Market')], default='MARKET', max_length=20),
        ),
    ]
