# Generated by Django 4.2.4 on 2023-11-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woo', '0006_alter_wooalgoorder_algo_type_alter_wooalgoorder_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wooalgoorder',
            name='realized_pnl',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
