# Generated by Django 4.2.4 on 2023-10-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algoorder',
            name='order_tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='algoorder',
            name='trade_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='algoorder',
            name='trigger_trade_price',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
