# Generated by Django 4.2.4 on 2023-10-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woo', '0003_wooalgoorder_and_more'),
        ('us', '0007_timeframegroup_max_consecutive_and_more'),
        ('us_orders', '0002_algoorder_order_tag_algoorder_trade_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us.timeframeklinesignal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woo.wooalgoorder')),
                ('reduce_only_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reduce_only_order', to='woo.wooalgoorder')),
            ],
        ),
        migrations.DeleteModel(
            name='AlgoOrder',
        ),
    ]
