# Generated by Django 4.2.4 on 2023-11-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us_orders', '0005_ordergroup_remove_order_order_unique_constraint_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('order', models.F('stop')), _negated=True), name='order_is_not_the_same_as_stop_constraint'),
        ),
    ]
