# Generated by Django 4.2.4 on 2023-11-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us_orders', '0006_order_order_is_not_the_same_as_stop_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order', 'indicator'), name='order_unique_constraint'),
        ),
    ]
