# Generated by Django 4.2.4 on 2023-11-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woo', '0005_wooalgoorder_woo_algo_order_type_is_sell_or_buy_constraint'),
        ('us_orders', '0007_remove_order_order_unique_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ordergroup',
            name='order_group_unique_constraint',
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='side',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='stop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_group_stop', to='woo.wooalgoorder'),
        ),
    ]
