# Generated by Django 4.2.4 on 2023-11-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us_orders', '0009_alter_ordergroup_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergroup',
            name='orders',
            field=models.ManyToManyField(related_name='order_groups', to='us_orders.order'),
        ),
    ]
