# Generated by Django 4.2.4 on 2024-02-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woo', '0007_alter_wooalgoorder_realized_pnl'),
        ('us', '0015_alter_timeframegroup_strategy_variables'),
        ('us_orders', '0011_order_previous_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='force_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='previous_indicators',
            field=models.ManyToManyField(blank=True, null=True, related_name='previous_indicators', to='us.timeframeklinesignal'),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='stop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_group_stop', to='woo.wooalgoorder'),
        ),
    ]
