# Generated by Django 4.2.4 on 2024-02-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0015_alter_timeframegroup_strategy_variables'),
        ('us_orders', '0012_order_force_close_alter_order_previous_indicators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='previous_indicators',
            field=models.ManyToManyField(blank=True, related_name='previous_indicators', to='us.timeframeklinesignal'),
        ),
    ]
