# Generated by Django 4.2.4 on 2023-10-18 16:46

from django.db import migrations, models
import django.db.models.deletion
import us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('us', '0007_timeframegroup_max_consecutive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlineDiagnosticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.PositiveBigIntegerField()),
                ('end_time', models.PositiveBigIntegerField()),
                ('kline_type', models.CharField(blank=True, default='Kline', editable=False, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.JSONField(blank=True, null=True)),
                ('incorrect_klines', models.ManyToManyField(to='us.kline')),
                ('symbol', models.ForeignKey(default=us.models.get_default_symbol_id, on_delete=django.db.models.deletion.CASCADE, to='us.symbol')),
            ],
            options={
                'verbose_name_plural': 'Kline diagnostics results',
            },
        ),
    ]
