# Generated by Django 4.2.4 on 2023-10-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_remove_klinediagnosticsresult_incorrect_klines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeframeklinesignal',
            name='timeframe_kline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='us.timeframekline'),
        ),
    ]
