# Generated by Django 4.2.4 on 2023-10-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0004_alter_timeframeklinesignal_timeframe_kline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeframegroup',
            name='quanity',
            field=models.DecimalField(decimal_places=6, default=0.1, max_digits=20),
        ),
    ]
