# Generated by Django 4.2.4 on 2023-10-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0006_rename_quanity_timeframegroup_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeframegroup',
            name='max_consecutive',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='timeframegroup',
            name='minutes_passed_since_last_active',
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='timeframegroup',
            name='stop_loss_difference',
            field=models.PositiveSmallIntegerField(default=900),
        ),
        migrations.AddField(
            model_name='timeframegroup',
            name='trigger_price_difference',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
