# Generated by Django 4.2.4 on 2023-11-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0007_timeframegroup_max_consecutive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeframe',
            name='type',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
    ]
