# Generated by Django 4.2.4 on 2023-11-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0008_alter_timeframe_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeframe',
            name='seconds',
        ),
        migrations.RemoveField(
            model_name='timeframe',
            name='type',
        ),
    ]
