# Generated by Django 4.2.4 on 2023-11-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0009_remove_timeframe_seconds_remove_timeframe_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timeframeklinesignal',
            constraint=models.CheckConstraint(check=models.Q(('type', 'SELL'), ('type', 'BUY'), _connector='OR'), name='timeframe_kline_signal_unique_constraint'),
        ),
    ]
