# Generated by Django 4.2.4 on 2023-11-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0014_strategyvariables_remove_timeframegroup_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeframegroup',
            name='strategy_variables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='us.strategyvariables'),
        ),
    ]
